routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group (['namespace'=>'Admin', 'middleware'=>['auth']],function () {
    Route::resource('admin', 'AdminController');
});

Route::get('/', 'IndexController@show')->name('index');
Route::get('/textnews{id}', 'NewsController@show')->name('textnews');

Route::post('/subscribe','SubscribeController@store')->name('subscribe');


Route::post ('/publishComment', 'CommentController@publishComment')->name('publishComment');

Route::get('/getNews', 'Admin\AdminController@getNews')->name('getNews');

Route::post('/destroy', 'Admin\AdminController@destroy')->name('destroy');

Auth::routes();

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
    protected $table = 'comments';

    protected $primaryKey = 'id';


    protected $fillable = [
        'newsId', 'commenterName', 'commentText',
    ];

    public function news (){
        return $this->belongsTo('App\News','id', 'newsId');
    }

}

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;



class News extends Model
{
    protected $table = 'news';

    protected $primaryKey = 'id';

    protected $fillable = [
        'title', 'summary', 'fulltext', 'images',
    ];

    public function comments (){
        return $this->hasMany('App\Comment','newsId', 'id');
    }

    //
}

app/Subscriber.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subscriber extends Model
{
    protected $table = 'subscribers';

    protected $primaryKey = 'id';

    protected $fillable = [
        'email',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreUpdateRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\News;
use App\Jobs\SendMessage;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.admin', ['news'=>News::orderBy('created_at','desc')]);

    }

    public function getNews(){
        $news = News::orderBy('created_at','desc')->get();
        return response()->json( $news, 200);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.createNews');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreUpdateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUpdateRequest $request)
    {
        //
        $news = new News;
        $news->title = $request->headnews;
        $news->summary = $request->summary;
        $news->fulltext = $request->fulltext;
        $news->images = $request->images;
        $news->save();

        SendMessage::dispatch();

        return redirect('admin');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return bool
     */
    public function show($id)
    {
        //
        return true;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $news = News::find($id);
        return view('admin.editNews',compact('news', 'id'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  StoreUpdateRequest $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUpdateRequest $request, $id)
    {
        //
        $news = News::find($id);
        $news->title = $request->heabnews;
        $news->title = $request->headnews;
        $news->summary = $request->summary;
        $news->fulltext = $request->fulltext;
        $news->images = $request->images;
        $news->save();
        return redirect('admin');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return bool
     */

    public function destroy(Request $request)
    {

        $news = News::find($request->input('id'));
        $news->delete();
        return $this->getNews();

    }


}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;


class CommentController extends Controller
{
    //
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function publishComment (Request $request){
        $comment = new Comment();
        $comment->newsId = $request->input('newsId');
        $comment->commenterName = $request->input('commentatorName');
        $comment->commentText = $request->input('textComment');

        if (!$comment->save()) {
            return response()->json(['comResult' => ''], 200);

        }else {
            return response()->json( $comment, 200);

        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;


}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\News;

class IndexController extends Controller
{
    //

    public function show(){
        return view('index', [
            'news'=>News::orderBy('created_at','desc')->get()
        ]);

    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\News;

class NewsController extends Controller
{
   

    public function show($id){

        $news = News::find($id);
        $comments = $news->comments;

        return view('textNews', [
            'news'=>$news,
            'comments'=>$comments
        ]);

    }
}

app/Http/Controllers/SubscribeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subscriber;


class SubscribeController extends Controller
{
    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request)
    {

        $subscriber = Subscriber::where('email', 'LIKE', $request->input('email'))->get();

        if (!$subscriber->isEmpty()) {
            $subscribeResult = 'Подписка на адрес '. $request->input('email') .' уже оформлена ранее';
            return response()->json(['subscribeResult' => $subscribeResult], 200);
        } else {

            $newSubscriber = new Subscriber;
            $newSubscriber->email = $request->email;
            $newSubscriber->save();
            $subscribeResult = 'Подписка на адрес ' . $request->input('email') . ' оформлена';
            return response()->json(['subscribeResult' => $subscribeResult], 200);

        }

    }


}

resources/views/admin/admin.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">
        <a href="{{route('admin.create')}}" class="btn btn-info"> @lang('messages.createNews')</a>
    </div>


    <div class="container-fluid col-lg-10">
        <br>
        <destroynews-component></destroynews-component>
    </div>

   @endsection

resources/views/admin/createNews.blade.php
@extends('layouts.app')


@section('content')

    <form class="form-horizontal" action="{{route('admin.store')}}" method="post">
        {{csrf_field()}}
       @include('admin.partials.forms')
    </form>


@endsection

resources/views/admin/editNews.blade.php
@extends('layouts.app')


@section('content')
    <form class="form-horizontal" action="{{route('admin.update',$news->id)}}" method="post">
        {{csrf_field()}}
        <input name="_method" type="hidden" value="PATCH">
        @include('admin.partials.forms')
    </form>

@endsection

resources/views/admin/partials/forms.blade.php
<div class="form-group">

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <label for="headnews" class="col-lg-1">@lang('messages.headnews')</label>
    <input type="text" class="form-control-lg col-lg-6" id="headnews" name="headnews" placeholder=@lang('messages.headnews')
           @if (isset ($news->id) )
           value="{{$news->title}}"
           @endif>

</div>

<div class="form-group">
    <label for="summary" class="col-lg-1" rows="2">@lang('messages.summary')</label>
    <textarea class="form-control-lg  col-lg-6" id="summary" name="summary" rows="2">@if (isset ($news->id)){{$news->summary}}@endif</textarea>
</div>


<div class="form-group  ">
    <label for="fulltext" class="col-lg-1">@lang('messages.fulltext')</label>
    <textarea class="form-control-lg  col-lg-6" id="fulltext" name="fulltext" rows="5" placeholder=@lang('messages.fulltext')>@if (isset ($news->id)){{$news->fullText}}@endif</textarea>
</div>

<div class="form-group">
    <label for="images" class="col-lg-1">@lang('messages.images')</label>
    <input type="text" class="form-control-lg col-lg-6" id="images" name="images" placeholder=@lang('messages.images')
    @if (isset ($news->id) )
            value="{{$news->images}}"
            @endif>
</div>


<button type="submit" class="btn btn-success">@lang('messages.publish')</button>

<a href="{{action('Admin\AdminController@index')}}" class="btn btn-info">@lang('messages.back')</a>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.template')

@section('content')


    <div class="row col-lg-12" id="app">
        @forelse($news as $newsone)

        <div  class="card bg-light mb-3 text-center col-lg-3 border-info">
            @if ($newsone->images)
            <img class="card-img-top img-responsive rounded"  alt="Card image cap" src={{asset($newsone->images)}}>
            @endif
            <div class="card-body">
                <h4 class="card-title">{{$newsone->title}}</h4>
                <p class="card-text">{{$newsone->summary}}</p>
                <a class="btn btn-primary" href={{route('textnews', ['id' => $newsone->id])}} >@lang('messages.learnMore')</a>
            </div>
            <div class="card-footer text-muted">
                {{$newsone->created_at}}
            </div>
        </div>
    @empty
        <p>@lang('messages.noNews')</p>
    @endforelse
    </div>
    @endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@lang('messages.nameSite')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    @lang('messages.home')
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">


                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>


</body>
</html>

resources/views/layouts/template.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ asset('css/news.css') }}" />


    <title>@lang('messages.nameSite')</title>
</head>
<body>


@section('navpanel')
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #eef2ff;" id="app">
        <img style="max-width:120px; margin-top: -7px;" class="navbar-brand"
             src={{asset('images/logo.png')}} alt="logo">


        <div class="collapse navbar-collapse" id="navbar1">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('index')}}">@lang('messages.home') <span
                                class="sr-only">(current)</span></a>
                </li>

            </ul>
            <div class="collapse navbar-collapse" id="navbar1">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href={{route('admin.index')}}>@lang('messages.admin') <span class="sr-only">(current)</span></a>
                    </li>

                </ul>
            </div>
            @show

            <subscribe-component></subscribe-component>

        </div>
    </nav>

        @yield('content')




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script src="{{ asset('js/app.js') }}" defer></script>



</body>
</html>

resources/views/textNews.blade.php
@extends('layouts.template')



@section('content')
    <div>
        <h3 class="display-4">{{$news->title}}</h3>
        <div class="col-lg-5">
            @if ($news->images)
                <img class="rounded img-responsive" alt="image" src={{asset($news->images)}} >@endif
        </div>
        <div>
            <p class="lead"> {{$news->fullText}}</p>
        </div>
    </div>

    <br>
    <div class="display" id="comments">
        <comments-component news-id="{{$news->id}} "
                            comment="@lang('messages.comment')"
                            allcomments="{{$comments}}">
        </comments-component>
    </div>
@endsection